#ifndef RSSNADV_H
#define RSSNADV_H

/* Generated with cbindgen:0.29.2 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdarg>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

namespace dtact {

/*
 `+`
 */
constexpr static const uint8_t ADD = 0;

/*
 Constant: numeric value lives in the `coefficient` field.
 */
constexpr static const uint8_t CONSTANT = 1;

/*
 `/`
 */
constexpr static const uint8_t DIV = 3;

/*
 Function: `kind_payload` carries the `FnId`.
 */
constexpr static const uint8_t FUNCTION = 3;

/*
 Maximum allowed depth of parenthesis / operator recursion.

 Each parse level requires two stack frames (`parse_expr_climbing` +
 `parse_atom`). In debug builds these frames are large enough that
 1024 levels can overflow the default 8 MB thread stack. 200 keeps
 the recursive depth ≈ 400 frames, which is safe on every target.
 */
constexpr static const uint16_t MAX_PAREN_DEPTH = 200;

/*
 `%` (IEEE-754 remainder)
 */
constexpr static const uint8_t MOD = 6;

/*
 `*`
 */
constexpr static const uint8_t MUL = 2;

/*
 unary `-`
 */
constexpr static const uint8_t NEG = 5;

/*
 The null sentinel for `i64` relative pointers.

 `i64::MIN` is chosen for the same reason as [`RelPtr::<T, i32>::NULL_OFFSET`]:
 a valid offset of ±2^63 is unreachable for any practical arena.
 */
constexpr static const int64_t RelPtr_NULL_OFFSET = INT64_MIN;

/*
 Number of independent shards. Picked to be ≥ a typical core count
 (32–128 cores on modern servers) while remaining cheap to
 allocate. 32 means each shard owns ~3 % of the keyspace on average.
 */
constexpr static const size_t NUM_SHARDS = 32;

/*
 Operator: `op_tag` carries the `OpKind`.
 */
constexpr static const uint8_t OPERATOR = 2;

/*
 `^`
 */
constexpr static const uint8_t POW = 4;

/*
 `-`
 */
constexpr static const uint8_t SUB = 1;

/*
 Variable: `kind_payload` carries the `SymbolId`.
 */
constexpr static const uint8_t VARIABLE = 0;

/*
 Return status codes for C-API function invocations.

 Values 0–6 are the original surface; 7–13 are new variants added to give
 C consumers richer diagnostics without needing to inspect Rust error types.
 */
enum class RssnStatus {
    /*
     Operation completed successfully.
     */
    RssnStatusSuccess = 0,
    /*
     A null pointer was passed for a mandatory parameter.
     */
    RssnStatusNullPointer = 1,
    /*
     Failed to parse expression.
     */
    RssnStatusParseError = 2,
    /*
     Failed to JIT compile the target expression.
     */
    RssnStatusCompilationError = 3,
    /*
     A panic occurred during execution.
     */
    RssnStatusPanic = 4,
    /*
     A C string argument was not valid UTF-8.
     */
    RssnStatusInvalidUtf8 = 5,
    /*
     A `DagNodeId` argument referred to an arena slot that doesn't
     exist (or is the null sentinel where one wasn't expected).
     */
    RssnStatusInvalidNodeId = 6,
    /*
     The DAG arena reached its maximum capacity (`u32::MAX - 1` nodes).
     */
    RssnStatusArenaFull = 7,
    /*
     Attempted to register a symbol that already exists in the registry.
     */
    RssnStatusDuplicateSymbol = 8,
    /*
     An underlying I/O operation failed (file open, read, write, or mmap).
     */
    RssnStatusStorageIo = 9,
    /*
     The on-disk arena format is corrupt or incompatible.
     */
    RssnStatusStorageFormat = 10,
    /*
     A rewrite rule conflicts with an existing rule in the registry.
     */
    RssnStatusRuleConflict = 11,
    /*
     SIMD batch operation received slices of different lengths.
     */
    RssnStatusSimdLengthMismatch = 12,
    /*
     A node was constructed with the wrong number of children for its operator.
     */
    RssnStatusInvalidArity = 13,
    /*
     A node descriptor referenced an invalid kind or out-of-range child index.
     */
    RssnStatusInvalidNode = 14,
    /*
     A caller-provided output buffer was too small to hold the result.
     */
    RssnStatusBufferTooSmall = 15,
};

/*
 The primary context for building symbolic expression DAGs.

 It coordinates the symbol registry, arena storage, and deduplication map
 to construct perfectly-shared Directed Acyclic Graphs.
 */
struct DagBuilder;

/*
 An index into the `DagArena`, identifying a specific `DagNode`.

 This is a lightweight handle (4 bytes) that can be freely copied
 and compared. It is only valid within the arena that created it.
 */
struct DagNodeId;

/*
 A function identifier, referencing a named function in the registry.

 Values `0..=6` are reserved as **intrinsic** identifiers, one per
 [`OpKind`] variant (matching its `#[repr(u8)]` discriminant). This
 lets built-in operators be expressed as `FnId` for the JIT/parallel
 engines that want to handle them uniformly alongside user functions.

 User-defined functions must use IDs ≥ [`FnId::FIRST_USER`].
 */
struct FnId;

/*
 Flags that describe algebraic properties of a node.
 */
struct NodeFlags;

/*
 Hash value computed by `rapidhash` for structural deduplication.

 Two nodes with the same `NodeHash` are structurally identical
 (modulo hash collisions, which are verified by full structural comparison).
 */
struct NodeHash;

template<typename T = void>
struct Option;

/*
 Opaque persistent JIT context. Holds the Cranelift `JitCompiler` so it
 can be reused across multiple `rssn_dag_compile_with_ctx` calls without
 re-paying the per-call ISA detection / module initialisation cost.
 */
struct RssnJitContext;

/*
 Opaque handle for a registered C rewrite rule registry.

 Create with [`rssn_rule_registry_new`]; free with [`rssn_rule_registry_free`].
 */
struct RssnRuleRegistry;

/*
 Opaque async simplification handle. Returned by
 [`rssn_dag_simplify_async_v2`]; pass to [`rssn_async_join`] to block
 until the fiber completes and obtain the result.

 The handle stores the `TaskHandle` value as a `u64` for C ABI
 compatibility. A value of `u64::MAX` signals an early error (null
 builder, etc.).
 */
struct RssnAsyncHandle {
    /*
     Internal fiber handle, or `u64::MAX` on error.
     */
    uint64_t mHandleId;
    /*
     Predicted simplified root (written by the fiber before completion).
     Zero until the fiber writes it; read only after [`rssn_async_join`].
     */
    uint32_t mSimplifiedRoot;
    /*
     Status code set by the fiber.
     */
    RssnStatus mStatus;

    RssnAsyncHandle(uint64_t const& aMHandleId,
                    uint32_t const& aMSimplifiedRoot,
                    RssnStatus const& aMStatus)
      : mHandleId(aMHandleId),
        mSimplifiedRoot(aMSimplifiedRoot),
        mStatus(aMStatus)
    {}

    bool operator==(const RssnAsyncHandle& aOther) const {
        return mHandleId == aOther.mHandleId &&
               mSimplifiedRoot == aOther.mSimplifiedRoot &&
               mStatus == aOther.mStatus;
    }
    bool operator!=(const RssnAsyncHandle& aOther) const {
        return mHandleId != aOther.mHandleId ||
               mSimplifiedRoot != aOther.mSimplifiedRoot ||
               mStatus != aOther.mStatus;
    }
};

/*
 Compact node descriptor for batch DAG construction.

 The caller allocates an array of these, fills them in topological order
 (children before parents), and passes the whole array to
 [`rssn_dag_batch_build`]. The output array receives the allocated IDs.

 Field semantics by `kind`:

 | kind | meaning | fields used |
 |------|---------|-------------|
 | 0 = Variable | leaf variable | `name[0..32]` |
 | 1 = Constant | leaf constant | `value` |
 | 2 = Add      | `child0 + child1` | `child0`, `child1` |
 | 3 = Sub      | `child0 - child1` | `child0`, `child1` |
 | 4 = Mul      | `child0 * child1` | `child0`, `child1` |
 | 5 = Div      | `child0 / child1` | `child0`, `child1` |
 | 6 = Pow      | `child0 ^ child1` | `child0`, `child1` |
 | 7 = Neg      | `-child0`         | `child0` |
 | 8 = Mod      | `child0 % child1` | `child0`, `child1` |

 `child0` and `child1` are **indices into the `out_ids` array** of the
 same batch call — they are NOT `DagNodeId` values. Index `u32::MAX`
 means "no child". This allows forward-reference-free batch construction.
 */
struct RssnNodeDesc {
    /*
     Constant value (used when `kind == 1`).
     */
    double mValue;
    /*
     Index into `out_ids` of this call for the first child.
     */
    uint32_t mChild0;
    /*
     Index into `out_ids` of this call for the second child.
     */
    uint32_t mChild1;
    /*
     Node kind discriminant (see table above).
     */
    uint8_t mKind;
    /*
     Null-terminated variable name (used when `kind == 0`).
     */
    uint8_t mName[31];

    RssnNodeDesc(double const& aMValue,
                 uint32_t const& aMChild0,
                 uint32_t const& aMChild1,
                 uint8_t const& aMKind,
                 uint8_t const& aMName[31])
      : mValue(aMValue),
        mChild0(aMChild0),
        mChild1(aMChild1),
        mKind(aMKind),
        mName(aMName)
    {}

};

/*
 C-compatible JIT optimisation configuration.

 Fields mirror [`crate::jit::compiler::OptConfig`]. Pass a pointer to this
 struct to [`rssn_dag_compile_with_opts`]; pass NULL to use the defaults.
 */
struct RssnOptConfig {
    /*
     Maximum integer exponent expanded without a `powf` call (default: 16).
     */
    uint32_t mMaxIntPow;
    /*
     Non-zero to expand `x^0.5` to a native `sqrt` instruction (default: 1).
     */
    uint32_t mExpandSqrt;
    /*
     Non-zero to replace `x / C` with `x * (1/C)` (default: 0).
     */
    uint32_t mAllowReciprocalMath;
    /*
     Non-zero to skip divide-by-zero guards when the denominator is proven
     non-zero by the analysis pass (default: 1).
     */
    uint32_t mElideNanGuard;
    /*
     Non-zero to reuse SSA values for repeated DAG sub-expressions (default: 1).
     */
    uint32_t mEnableCse;

    RssnOptConfig(uint32_t const& aMMaxIntPow,
                  uint32_t const& aMExpandSqrt,
                  uint32_t const& aMAllowReciprocalMath,
                  uint32_t const& aMElideNanGuard,
                  uint32_t const& aMEnableCse)
      : mMaxIntPow(aMMaxIntPow),
        mExpandSqrt(aMExpandSqrt),
        mAllowReciprocalMath(aMAllowReciprocalMath),
        mElideNanGuard(aMElideNanGuard),
        mEnableCse(aMEnableCse)
    {}

    bool operator==(const RssnOptConfig& aOther) const {
        return mMaxIntPow == aOther.mMaxIntPow &&
               mExpandSqrt == aOther.mExpandSqrt &&
               mAllowReciprocalMath == aOther.mAllowReciprocalMath &&
               mElideNanGuard == aOther.mElideNanGuard &&
               mEnableCse == aOther.mEnableCse;
    }
    bool operator!=(const RssnOptConfig& aOther) const {
        return mMaxIntPow != aOther.mMaxIntPow ||
               mExpandSqrt != aOther.mExpandSqrt ||
               mAllowReciprocalMath != aOther.mAllowReciprocalMath ||
               mElideNanGuard != aOther.mElideNanGuard ||
               mEnableCse != aOther.mEnableCse;
    }
};

/*
 Configuration for E-graph equality saturation.

 Passed by value across the FFI boundary; zero-initialise for defaults.
 */
struct RssnEGraphConfig {
    /*
     Maximum saturation rounds (0 → use library default of 8).
     */
    uint32_t mMaxRounds;
    /*
     Maximum equivalence merges before stopping (0 → default 512).
     */
    uint32_t mMaxMerges;
    /*
     Maximum new nodes the E-graph may create via rewrites (0 → default 1024).
     */
    uint32_t mMaxNewNodes;
    /*
     Non-zero → enable strict IEEE 754 signed-zero semantics.

     When set, `x + (-0.0)` will **not** be simplified to `x`, matching
     `-fno-unsafe-math-optimizations`. Default (0) uses `-fno-signed-zeros`.
     */
    uint8_t mStrictIeee754SignedZero;

    RssnEGraphConfig(uint32_t const& aMMaxRounds,
                     uint32_t const& aMMaxMerges,
                     uint32_t const& aMMaxNewNodes,
                     uint8_t const& aMStrictIeee754SignedZero)
      : mMaxRounds(aMMaxRounds),
        mMaxMerges(aMMaxMerges),
        mMaxNewNodes(aMMaxNewNodes),
        mStrictIeee754SignedZero(aMStrictIeee754SignedZero)
    {}

    bool operator==(const RssnEGraphConfig& aOther) const {
        return mMaxRounds == aOther.mMaxRounds &&
               mMaxMerges == aOther.mMaxMerges &&
               mMaxNewNodes == aOther.mMaxNewNodes &&
               mStrictIeee754SignedZero == aOther.mStrictIeee754SignedZero;
    }
    bool operator!=(const RssnEGraphConfig& aOther) const {
        return mMaxRounds != aOther.mMaxRounds ||
               mMaxMerges != aOther.mMaxMerges ||
               mMaxNewNodes != aOther.mMaxNewNodes ||
               mStrictIeee754SignedZero != aOther.mStrictIeee754SignedZero;
    }
};

/*
 A C-callable rewrite rule for the E-graph.

 Called for each node during saturation. Return the ID of an equivalent
 node to merge into the same e-class, or `u32::MAX` to decline.

 `kind`       — discriminant of the current node's kind (see `RssnKind`).
 `children`   — pointer to the *canonical* child IDs (length `n_children`).
 `n_children` — number of children.
 `user_data`  — opaque pointer forwarded unchanged from the registration call.
 */
using RssnEGraphRuleCallback = uint32_t(*)(DagBuilder *builder,
                                           uint8_t kind,
                                           const uint32_t *children,
                                           uint32_t n_children,
                                           void *user_data);

/*
 C-compatible simplification configuration.

 Pass a pointer to this struct to [`rssn_dag_simplify_with_config`] to
 override the default heuristic parameters. Pass NULL to use defaults.
 */
struct RssnSimplifyConfig {
    /*
     Maximum rewrite depth (default: 10).
     */
    uint32_t mMaxDepth;
    /*
     Wall-clock timeout in milliseconds (default: 500).
     */
    uint64_t mTimeoutMs;
    /*
     Approximate-pruning aggressiveness in `[0.0, 1.0]` (default: 0.1).
     */
    double mAggressiveness;

    RssnSimplifyConfig(uint32_t const& aMMaxDepth,
                       uint64_t const& aMTimeoutMs,
                       double const& aMAggressiveness)
      : mMaxDepth(aMMaxDepth),
        mTimeoutMs(aMTimeoutMs),
        mAggressiveness(aMAggressiveness)
    {}

    bool operator==(const RssnSimplifyConfig& aOther) const {
        return mMaxDepth == aOther.mMaxDepth &&
               mTimeoutMs == aOther.mTimeoutMs &&
               mAggressiveness == aOther.mAggressiveness;
    }
    bool operator!=(const RssnSimplifyConfig& aOther) const {
        return mMaxDepth != aOther.mMaxDepth ||
               mTimeoutMs != aOther.mTimeoutMs ||
               mAggressiveness != aOther.mAggressiveness;
    }
};

/*
 Type for a C-callable `extern "C" fn(f64) -> f64`.
 */
using RssnCustomFn1 = double(*)(double);

/*
 Type for a C-callable `extern "C" fn(f64, f64) -> f64`.
 */
using RssnCustomFn2 = double(*)(double,
                                double);

/*
 Type for a C-callable `extern "C" fn(f64, f64, f64) -> f64`.
 */
using RssnCustomFn3 = double(*)(double,
                                double,
                                double);

/*
 C-callable rewrite rule callback.

 - `builder`: pointer to the `DagBuilder`; call `rssn_dag_*` to create nodes.
 - `kind`: node kind discriminant (see [`RssnKind`]).
 - `children`: pointer to an array of child node ids (length `n_children`).
 - `n_children`: number of children.
 - `user_data`: the opaque pointer supplied at registration time.

 Return the replacement node id, or `u32::MAX` to leave the node unchanged
 (pass to the next rule).
 */
using RssnRuleCallback = uint32_t(*)(DagBuilder *builder,
                                     uint8_t kind,
                                     const uint32_t *children,
                                     uint32_t n_children,
                                     void *user_data);









extern "C" {

/*
 Blocks until the fiber behind `handle` completes, then frees the handle
 and writes the result to `*out_root` (if non-null).

 Returns the final [`RssnStatus`]. After this call, `builder` may be freed.

 # Safety

 `handle` must have been obtained from [`rssn_dag_simplify_async_v2`] and
 must not be used after this call.
 */

RssnStatus rssn_async_join(RssnAsyncHandle *aHandle,
                           uint32_t *aOutRoot)
;

/*
 Allocates a new addition node in the DAG: `lhs + rhs`.

 # Safety

 `builder` must be a valid, non-null pointer to a `DagBuilder` from [`rssn_dag_new`].
 */

uint32_t rssn_dag_add(DagBuilder *aBuilder,
                      uint32_t aLhs,
                      uint32_t aRhs)
;

/*
 Creates an addition node. Status-returning variant.

 # Safety

 - `builder` must be a valid, non-null pointer to a `DagBuilder` from [`rssn_dag_new`].
 - `out_id` must be a valid, non-null, writable `u32` pointer.
 */

RssnStatus rssn_dag_add_v2(DagBuilder *aBuilder,
                           uint32_t aLhs,
                           uint32_t aRhs,
                           uint32_t *aOutId)
;

/*
 Builds `n` DAG nodes in a single FFI call, writing allocated node IDs
 into `out_ids`.

 Nodes are processed in order `0..n`. Children are referenced by their
 **index in the batch** (not their `DagNodeId`); the builder translates
 indices to IDs after allocating each node.

 Returns `RssnStatus::Success` on success. On any error the output array
 may be partially populated — already-built nodes remain valid.

 # Safety

 - `builder` must be a valid, non-null `DagBuilder` from `rssn_dag_new`.
 - `descs` must point to an array of at least `n` `RssnNodeDesc` values,
   valid for the duration of this call.
 - `out_ids` must point to a writable array of at least `n` `u32` values.
 - Children referenced by `child0`/`child1` must have indices strictly
   less than the current node's index (topological order).
 */

RssnStatus rssn_dag_batch_build(DagBuilder *aBuilder,
                                const RssnNodeDesc *aDescs,
                                uint32_t aN,
                                uint32_t *aOutIds)
;

/*
 Builds a function-call node for a previously interned function.

 `args` points to an array of `n_args` node ids. The node ids must all be
 valid (not `u32::MAX`).

 Returns the new node id, or `u32::MAX` on error.

 # Safety

 - `builder` must be a valid, non-null pointer from [`rssn_dag_new`].
 - `args` must point to an array of at least `n_args` valid `u32` values,
   or be null when `n_args == 0`.
 */

uint32_t rssn_dag_call_fn(DagBuilder *aBuilder,
                          uint32_t aFnId,
                          const uint32_t *aArgs,
                          uint32_t aNArgs)
;

/*
 Builds a function-call node. Status-returning variant.

 # Safety

 - `builder` must be a valid, non-null pointer from [`rssn_dag_new`].
 - `args` must point to an array of at least `n_args` valid `u32` values,
   or be null when `n_args == 0`.
 - `out_id` must be a valid, non-null writable `u32` pointer.
 */

RssnStatus rssn_dag_call_fn_v2(DagBuilder *aBuilder,
                               uint32_t aFnId,
                               const uint32_t *aArgs,
                               uint32_t aNArgs,
                               uint32_t *aOutId)
;

/*
 JIT compiles a target expression and writes the native function pointer to `out_fn`.

 `out_fn` can be called via `rssn_dag_execute` or cast directly as `double (*)(const double*)`.

 # Safety

 - `builder` must be a valid, non-null pointer to a `DagBuilder` from [`rssn_dag_new`].
 - `out_fn` must be a valid, non-null pointer to a `*mut c_void` that the function will write to.
 - The compiled function pointer written to `*out_fn` remains valid until the `JITModule`
   backing this compiler is dropped. Do not call it after that.
 */

RssnStatus rssn_dag_compile(DagBuilder *aBuilder,
                            uint32_t aRoot,
                            void **aOutFn)
;

/*
 JIT compiles a target expression and writes the native function pointer to `out_fn`.

 `out_fn` can be called via `rssn_dag_execute` or cast directly as `double (*)(const double*)`.
 */

RssnStatus rssn_dag_compile(DagBuilder *aBuilder,
                            uint32_t aRoot,
                            void **aOutFn)
;

/*
 JIT compiles a target expression. Status-returning variant.

 On `Success`, writes the compiled function pointer to `*out_fn`.

 # Safety

 - `builder` must be a valid, non-null pointer to a `DagBuilder` from [`rssn_dag_new`].
 - `out_fn` must be a valid, non-null, writable `*mut c_void` pointer.
 - The compiled function pointer remains valid until the `JITModule` is dropped.
 */

RssnStatus rssn_dag_compile_v2(DagBuilder *aBuilder,
                               uint32_t aRoot,
                               void **aOutFn)
;

/*
 JIT compiles a target expression (stub for non-JIT builds).

 Always returns [`RssnStatus::CompilationError`] when the `cranelift-jit`
 feature is not enabled.
 */

RssnStatus rssn_dag_compile_v2(DagBuilder *aBuilder,
                               uint32_t aRoot,
                               void ***aOutFn)
;

/*
 Compiles a DAG expression using a persistent JIT context.

 Reuses the Cranelift module stored in `ctx`, skipping the per-call
 ISA detection + module setup that `rssn_dag_compile` pays. On
 `Success`, writes the compiled function pointer to `*out_fn`.
 */

RssnStatus rssn_dag_compile_with_ctx(RssnJitContext *aCtx,
                                     DagBuilder *aBuilder,
                                     uint32_t aRoot,
                                     void **aOutFn)
;

/*
 Stub for non-JIT builds: always returns `CompilationError`.
 */

RssnStatus rssn_dag_compile_with_ctx(void *aCtx,
                                     DagBuilder *aBuilder,
                                     uint32_t aRoot,
                                     void **aOutFn)
;

/*
 Compiles a DAG expression with explicit optimisation knobs.

 If `opts` is NULL, uses [`RssnOptConfig`] defaults (equivalent to
 [`rssn_dag_compile_v2`]).

 # Safety

 - `ctx` must be a valid, non-null pointer from [`rssn_jit_context_new`].
 - `builder` must be a valid, non-null pointer from [`rssn_dag_new`].
 - `out_fn` must be a valid, non-null writable pointer.
 - If `opts` is non-null it must point to a valid [`RssnOptConfig`].
 */

RssnStatus rssn_dag_compile_with_opts(RssnJitContext *aCtx,
                                      DagBuilder *aBuilder,
                                      uint32_t aRoot,
                                      const RssnOptConfig *aOpts,
                                      void **aOutFn)
;

/*
 Stub for non-JIT builds: always returns `CompilationError`.
 */

RssnStatus rssn_dag_compile_with_opts(void *aCtx,
                                      DagBuilder *aBuilder,
                                      uint32_t aRoot,
                                      const void *aOpts,
                                      void **aOutFn)
;

/*
 Allocates a new constant node in the DAG.

 # Safety

 `builder` must be a valid, non-null pointer to a `DagBuilder` from [`rssn_dag_new`].
 */

uint32_t rssn_dag_constant(DagBuilder *aBuilder,
                           double aVal)
;

/*
 Creates a new constant node. Status-returning variant.

 # Safety

 - `builder` must be a valid, non-null pointer to a `DagBuilder` from [`rssn_dag_new`].
 - `out_id` must be a valid, non-null, writable `u32` pointer.
 */

RssnStatus rssn_dag_constant_v2(DagBuilder *aBuilder,
                                double aVal,
                                uint32_t *aOutId)
;

/*
 Allocates a division node: `lhs / rhs`.

 Returns `u32::MAX` on error or null input.

 # Safety

 `builder` must be a valid, non-null pointer from [`rssn_dag_new`].
 */

uint32_t rssn_dag_div(DagBuilder *aBuilder,
                      uint32_t aLhs,
                      uint32_t aRhs)
;

/*
 Allocates a division node. Status-returning variant.

 # Safety

 - `builder` must be a valid, non-null pointer from [`rssn_dag_new`].
 - `out_id` must be a valid, non-null writable `u32` pointer.
 */

RssnStatus rssn_dag_div_v2(DagBuilder *aBuilder,
                           uint32_t aLhs,
                           uint32_t aRhs,
                           uint32_t *aOutId)
;

/*
 Runs E-graph equality saturation on `root` and returns the cheapest
 equivalent node ID, or `u32::MAX` on error.

 # C example

 ```c
 uint32_t best = rssn_dag_egraph_saturate_extract(
     builder, expr_id,
     (RssnEGraphConfig){ .max_rounds = 4, .max_merges = 256, .max_new_nodes = 512 },
     NULL, 0,   /* no user rules */
     NULL
 );
 ```

 # Safety

 - `builder` must be a valid, non-null `DagBuilder` from `rssn_dag_new`.
 - If `rules` is non-null, `n_rules` must be the number of valid callback
   pointers in the array.
 - `user_data` pointers must remain valid for the duration of this call.
 */

RssnStatus rssn_dag_egraph_saturate_extract(DagBuilder *aBuilder,
                                            uint32_t aRoot,
                                            RssnEGraphConfig aCfg,
                                            const RssnEGraphRuleCallback *aRules,
                                            uint32_t aNRules,
                                            uint32_t *aOut)
;

/*
 Executes a previously compiled JIT function with the given variable input array.

 # Safety

 - `func` must be a valid function pointer previously written by [`rssn_dag_compile`],
   with signature `double (*)(const double*)`.
 - `variables` must be a valid pointer to an array of at least as many `f64` values
   as there are distinct variables in the compiled expression, ordered by `SymbolId`.
 - Both pointers must remain valid for the duration of this call.
 */

double rssn_dag_execute(const void *aFunc,
                        const double *aVariables)
;

/*
 Executes a previously compiled JIT function with the given variable input array.
 */

double rssn_dag_execute(const void *aFunc,
                        const double *aVariables)
;

/*
 Executes a previously compiled JIT function. Status-returning variant.

 On `Success`, writes the result to `*out_val`.

 # Safety

 - `func` must be a valid function pointer previously written by [`rssn_dag_compile`].
 - `variables` must be a valid pointer to an array of at least as many `f64` values
   as there are variables in the compiled expression, ordered by `SymbolId`.
 - `out_val` must be a valid, non-null, writable `f64` pointer.
 - All pointers must remain valid for the duration of this call.
 */

RssnStatus rssn_dag_execute_v2(const void *aFunc,
                               const double *aVariables,
                               double *aOutVal)
;

/*
 Executes a previously compiled JIT function (stub for non-JIT builds).
 */

RssnStatus rssn_dag_execute_v2(const void *aFunc,
                               const double *aVariables,
                               double *aOutVal)
;

/*
 Releases the memory of a previously allocated `DagBuilder`.

 # Safety

 `builder` must be a pointer previously returned by [`rssn_dag_new`], or NULL.
 After this call the pointer is dangling and must not be used.
 Passing a pointer not from `rssn_dag_new`, or freeing twice, is undefined behaviour.
 */

void rssn_dag_free(DagBuilder *aBuilder)
;

/*
 Writes the packed arena snapshot to a caller-provided byte buffer.

 On success, `*bytes_written` receives the number of bytes written.
 Call once with `buf = NULL` to query the required buffer size
 (`*bytes_written` will be the needed byte count and the return value
 is `RssnStatus::Success`).

 The layout is: a little-endian `u64` node count, then `n × 32` bytes
 of packed node data (`PackedDagNode`), then a little-endian `u64` pool
 count, then `pool_count × 4` bytes of `u32` child IDs. Alignment of
 `buf` to 8 bytes is required.

 # Safety

 - `builder` must be a valid, non-null `DagBuilder`.
 - If `buf` is non-null, it must point to at least `buf_len` bytes of
   writable memory, correctly aligned to 8 bytes.
 - `bytes_written` must be a valid non-null pointer to a `u64`.
 */

RssnStatus rssn_dag_get_packed(const DagBuilder *aBuilder,
                               uint8_t *aBuf,
                               size_t aBufLen,
                               size_t *aBytesWritten)
;

/*
 Interns a function name and returns its numeric `FnId`.

 The returned id can be used with [`rssn_dag_call_fn`] to build
 function-call nodes, and with the JIT custom-function registration
 APIs to bind native implementations.

 Returns `u32::MAX` on null input or if interning fails.

 # Safety

 - `builder` must be a valid, non-null pointer from [`rssn_dag_new`].
 - `name` must be a valid, non-null, null-terminated C string.
 */

uint32_t rssn_dag_intern_function(DagBuilder *aBuilder,
                                  const char *aName)
;

/*
 Allocates a modulo node: `lhs % rhs`.

 Returns `u32::MAX` on error or null input.

 # Safety

 `builder` must be a valid, non-null pointer from [`rssn_dag_new`].
 */

uint32_t rssn_dag_mod(DagBuilder *aBuilder,
                      uint32_t aLhs,
                      uint32_t aRhs)
;

/*
 Allocates a modulo node. Status-returning variant.

 # Safety

 - `builder` must be a valid, non-null pointer from [`rssn_dag_new`].
 - `out_id` must be a valid, non-null writable `u32` pointer.
 */

RssnStatus rssn_dag_mod_v2(DagBuilder *aBuilder,
                           uint32_t aLhs,
                           uint32_t aRhs,
                           uint32_t *aOutId)
;

/*
 Allocates a multiplication node: `lhs * rhs`.

 Returns `u32::MAX` on error or null input.

 # Safety

 `builder` must be a valid, non-null pointer from [`rssn_dag_new`].
 */

uint32_t rssn_dag_mul(DagBuilder *aBuilder,
                      uint32_t aLhs,
                      uint32_t aRhs)
;

/*
 Allocates a multiplication node. Status-returning variant.

 # Safety

 - `builder` must be a valid, non-null pointer from [`rssn_dag_new`].
 - `out_id` must be a valid, non-null writable `u32` pointer.
 */

RssnStatus rssn_dag_mul_v2(DagBuilder *aBuilder,
                           uint32_t aLhs,
                           uint32_t aRhs,
                           uint32_t *aOutId)
;

/*
 Allocates a unary negation node: `-operand`.

 Returns `u32::MAX` on error or null input.

 # Safety

 `builder` must be a valid, non-null pointer from [`rssn_dag_new`].
 */

uint32_t rssn_dag_neg(DagBuilder *aBuilder,
                      uint32_t aOperand)
;

/*
 Allocates a unary negation node. Status-returning variant.

 # Safety

 - `builder` must be a valid, non-null pointer from [`rssn_dag_new`].
 - `out_id` must be a valid, non-null writable `u32` pointer.
 */

RssnStatus rssn_dag_neg_v2(DagBuilder *aBuilder,
                           uint32_t aOperand,
                           uint32_t *aOutId)
;

/*
 Creates a new `DagBuilder` context.

 Returns a raw pointer to the builder, or NULL if creation failed or panicked.
 The returned pointer must be freed exactly once via [`rssn_dag_free`].
 */

DagBuilder *rssn_dag_new()
;

/*
 Parses a mathematical expression from a C string into the DAG.

 The expression uses the standard infix syntax: `+`, `-`, `*`, `/`,
 `^` (exponentiation), `%` (modulo), parentheses, numeric literals,
 and identifier names for variables.

 On `Success`, writes the root node id of the parsed expression to
 `*out_id`. On failure returns [`RssnStatus::ParseError`].

 # Safety

 - `builder` must be a valid, non-null pointer from [`rssn_dag_new`].
 - `expr` must be a valid, non-null, null-terminated C string.
 - `out_id` must be a valid, non-null writable `u32` pointer.
 */

RssnStatus rssn_dag_parse(DagBuilder *aBuilder,
                          const char *aExpr,
                          uint32_t *aOutId)
;

/*
 Allocates an exponentiation node: `base ^ exp`.

 Returns `u32::MAX` on error or null input.

 # Safety

 `builder` must be a valid, non-null pointer from [`rssn_dag_new`].
 */

uint32_t rssn_dag_pow(DagBuilder *aBuilder,
                      uint32_t aBase,
                      uint32_t aExp)
;

/*
 Allocates an exponentiation node. Status-returning variant.

 # Safety

 - `builder` must be a valid, non-null pointer from [`rssn_dag_new`].
 - `out_id` must be a valid, non-null writable `u32` pointer.
 */

RssnStatus rssn_dag_pow_v2(DagBuilder *aBuilder,
                           uint32_t aBase,
                           uint32_t aExp,
                           uint32_t *aOutId)
;

/*
 Simplifies a target expression using the default heuristic engine.

 Returns the new root node index of the simplified expression.

 # Safety

 `builder` must be a valid, non-null pointer to a `DagBuilder` from [`rssn_dag_new`].
 */

uint32_t rssn_dag_simplify(DagBuilder *aBuilder,
                           uint32_t aRoot)
;

/*
 Fires a simplification fiber and returns an opaque handle.

 The caller must call [`rssn_async_join`] before freeing `builder`, making
 the use-after-free hazard explicit and auditable from C.

 The returned [`RssnAsyncHandle`] must be freed with [`rssn_async_join`].
 */

RssnAsyncHandle *rssn_dag_simplify_async(DagBuilder *aBuilder,
                                         uint32_t aRoot)
;

/*
 Simplifies an expression. Status-returning variant.

 # Safety

 - `builder` must be a valid, non-null pointer to a `DagBuilder` from [`rssn_dag_new`].
 - `out_id` must be a valid, non-null, writable `u32` pointer.
 */

RssnStatus rssn_dag_simplify_v2(DagBuilder *aBuilder,
                                uint32_t aRoot,
                                uint32_t *aOutId)
;

/*
 Simplifies an expression using a caller-supplied configuration.

 If `config` is NULL, behaves identically to [`rssn_dag_simplify_v2`].

 # Safety

 - `builder` must be a valid, non-null pointer to a `DagBuilder`.
 - `out_id` must be a valid, non-null, writable `u32` pointer.
 - If `config` is non-null, it must point to a valid `RssnSimplifyConfig`.
 */

RssnStatus rssn_dag_simplify_with_config(DagBuilder *aBuilder,
                                         uint32_t aRoot,
                                         const RssnSimplifyConfig *aConfig,
                                         uint32_t *aOutId)
;

/*
 Like [`rssn_dag_egraph_saturate_extract`] but also enables the E-graph
 pass inside the full heuristic simplification pipeline and returns the
 result after both passes.

 # Safety

 Same as `rssn_dag_egraph_saturate_extract`.
 */

RssnStatus rssn_dag_simplify_with_egraph(DagBuilder *aBuilder,
                                         uint32_t aRoot,
                                         RssnEGraphConfig aEgraphCfg,
                                         uint32_t *aOut)
;

/*
 Simplifies an expression using a caller-supplied C rule registry and configuration.

 If `registry` is NULL, only the built-in heuristic patterns are applied.
 If `config` is NULL, defaults are used.

 # Safety

 - `builder` and `out_id` must be valid, non-null pointers.
 - If `registry` is non-null it must be from [`rssn_rule_registry_new`].
 - If `config` is non-null it must point to a valid [`RssnSimplifyConfig`].
 */

RssnStatus rssn_dag_simplify_with_rules(DagBuilder *aBuilder,
                                        uint32_t aRoot,
                                        RssnRuleRegistry *aRegistry,
                                        const RssnSimplifyConfig *aConfig,
                                        uint32_t *aOutId)
;

/*
 Allocates a subtraction node: `lhs - rhs`.

 Returns `u32::MAX` on error or null input.

 # Safety

 `builder` must be a valid, non-null pointer from [`rssn_dag_new`].
 */

uint32_t rssn_dag_sub(DagBuilder *aBuilder,
                      uint32_t aLhs,
                      uint32_t aRhs)
;

/*
 Allocates a subtraction node. Status-returning variant.

 # Safety

 - `builder` must be a valid, non-null pointer from [`rssn_dag_new`].
 - `out_id` must be a valid, non-null writable `u32` pointer.
 */

RssnStatus rssn_dag_sub_v2(DagBuilder *aBuilder,
                           uint32_t aLhs,
                           uint32_t aRhs,
                           uint32_t *aOutId)
;

/*
 Allocates a new variable node in the DAG.

 Returns the index of the variable node, or `u32::MAX` if a panic
 occurred, the builder was null, or `name` was not valid UTF-8.

 Looks up `name` zero-allocation on the hot path:
 [`CStr::to_bytes`] → `SymbolRegistry::intern_bytes`. Only the
 first time a given name is interned does an allocation happen
 (`ffi_review §2`).

 # Safety

 - `builder` must be a valid, non-null pointer to a `DagBuilder` from [`rssn_dag_new`].
 - `name` must be a valid, non-null, null-terminated C string valid for the duration of
   this call.
 */

uint32_t rssn_dag_variable(DagBuilder *aBuilder,
                           const char *aName)
;

/*
 Creates a new variable node. Status-returning variant.

 On `Success`, writes the new node id to `*out_id`.

 # Safety

 - `builder` must be a valid, non-null pointer to a `DagBuilder` from [`rssn_dag_new`].
 - `name` must be a valid, non-null, null-terminated C string valid for this call.
 - `out_id` must be a valid, non-null, writable `u32` pointer.
 */

RssnStatus rssn_dag_variable_v2(DagBuilder *aBuilder,
                                const char *aName,
                                uint32_t *aOutId)
;

/*
 Frees a persistent JIT context previously created by
 [`rssn_jit_context_new`]. Passing NULL is a safe no-op.
 */

void rssn_jit_context_free(RssnJitContext *aCtx)
;

/*
 Stub for non-JIT builds: no-op.
 */

void rssn_jit_context_free(void *aCtx)
;

/*
 Creates a new persistent JIT context.

 Returns a raw pointer to the context, or NULL if construction panicked.
 The caller must free the returned context with [`rssn_jit_context_free`].
 */

RssnJitContext *rssn_jit_context_new()
;

/*
 Stub for non-JIT builds: always returns NULL.
 */

void *rssn_jit_context_new()
;

/*
 Registers a one-argument native function with the persistent JIT context
 so it can be called from compiled expressions.

 The `fn_id` must have been obtained via [`rssn_dag_intern_function`].
 The `func` pointer must remain valid for the lifetime of the JIT context.

 # Safety

 `func` must be a valid function pointer with the signature `double(double)`.
 */

RssnStatus rssn_jit_register_fn_1(RssnJitContext *aCtx,
                                  uint32_t aFnId,
                                  Option<RssnCustomFn1> aFunc)
;

/*
 Registers a one-argument native function (stub for non-JIT builds).
 */

RssnStatus rssn_jit_register_fn_1(void *aCtx,
                                  uint32_t aFnId,
                                  double (*aFunc)(double))
;

/*
 Registers a two-argument native function with the persistent JIT context.

 # Safety

 `func` must be a valid function pointer with the signature `double(double, double)`.
 */

RssnStatus rssn_jit_register_fn_2(RssnJitContext *aCtx,
                                  uint32_t aFnId,
                                  Option<RssnCustomFn2> aFunc)
;

/*
 Registers a two-argument native function (stub for non-JIT builds).
 */

RssnStatus rssn_jit_register_fn_2(void *aCtx,
                                  uint32_t aFnId,
                                  double (*aFunc)(double,
                                                  double))
;

/*
 Registers a three-argument native function with the persistent JIT context.

 # Safety

 `func` must be a valid function pointer with the signature `double(double, double, double)`.
 */

RssnStatus rssn_jit_register_fn_3(RssnJitContext *aCtx,
                                  uint32_t aFnId,
                                  Option<RssnCustomFn3> aFunc)
;

/*
 Registers a three-argument native function (stub for non-JIT builds).
 */

RssnStatus rssn_jit_register_fn_3(void *aCtx,
                                  uint32_t aFnId,
                                  double (*aFunc)(double,
                                                  double,
                                                  double))
;

/*
 Registers a C callback as a rewrite rule.

 - `name`: human-readable rule name (null-terminated C string, for fingerprinting).
 - `callback`: the rule function; called during simplification for each node.
 - `priority`: higher values are tried first (default-priority rules use 0).
 - `kind_filter`: if non-negative, the rule is only tried for nodes with this
   kind discriminant (see [`RssnKind`]). Pass `-1` for a wildcard rule.
 - `user_data`: opaque pointer forwarded to every callback invocation.

 # Safety

 - `registry` must be a valid, non-null pointer from [`rssn_rule_registry_new`].
 - `name` must be a valid, non-null, null-terminated C string.
 - `callback` must be a valid, non-null function pointer.
 - `user_data` must remain valid for the lifetime of the registry.
 */

RssnStatus rssn_rule_register(RssnRuleRegistry *aRegistry,
                              const char *aName,
                              Option<RssnRuleCallback> aCallback,
                              int32_t aPriority,
                              int32_t aKindFilter,
                              void *aUserData)
;

/*
 Frees a rule registry previously created by [`rssn_rule_registry_new`].

 Passing NULL is a safe no-op.

 # Safety

 `registry` must be a pointer returned by [`rssn_rule_registry_new`] or NULL.
 */

void rssn_rule_registry_free(RssnRuleRegistry *aRegistry)
;

/*
 Creates a new, empty rule registry.

 The returned pointer must be freed with [`rssn_rule_registry_free`].
 Returns NULL if construction panics.
 */

RssnRuleRegistry *rssn_rule_registry_new()
;

}  // extern "C"

}  // namespace dtact

#endif  // RSSNADV_H
