#ifndef RSSN_ADVANCED_H
#define RSSN_ADVANCED_H

/* Generated with cbindgen:0.29.2 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdarg>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

namespace rssn-advanced {

}  // namespace rssn-advanced

#endif  // RSSN_ADVANCED_H
