#ifndef RSSN_ADVANCED_H
#define RSSN_ADVANCED_H

/* Generated with cbindgen:0.29.2 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
namespace rssn-advanced {
#endif  // __cplusplus

#ifdef __cplusplus
}  // namespace rssn-advanced
#endif  // __cplusplus

#endif  /* RSSN_ADVANCED_H */
