name: Miri

on:
  push:
    branches: [trunk, main, 'v*.x', 'ci/*']
  pull_request:
    branches: [trunk, main, 'v*.x']

env:
  CARGO_TERM_COLOR: always
  MIRIFLAGS: "-Zmiri-disable-isolation"

jobs:
  miri:
    name: Miri
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: dtolnay/rust-toolchain@5b842231ba77f5c045dba54ac5560fed2db780e2 # nightly
        with:
          components: miri
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
      - name: cargo miri setup
        run: cargo miri setup
      - name: cargo miri test
        run: cargo miri test --all-features --no-fail-fast
